# Generated by Django 6.0.1 on 2026-03-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kid_mode_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
