# Generated by Django 6.0.1 on 2026-02-10 22:12

import apps.video.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('video_file', models.FileField(upload_to=apps.video.models.user_video_upload_path)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/%Y/%m/')),
                ('duration', models.DurationField(help_text='Video duration')),
                ('age_rating', models.CharField(blank=True, choices=[('6+', '6+'), ('10+', '10+'), ('14+', '14+')], max_length=10, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_kids_friendly', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='category.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='videos', to='category.tag')),
                ('upload_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['is_published', '-published_at'], name='video_video_is_publ_687da6_idx'), models.Index(fields=['is_trending'], name='video_video_is_tren_065243_idx'), models.Index(fields=['category'], name='video_video_categor_be82a4_idx')],
            },
        ),
    ]
