# Generated by Django 6.0.1 on 2026-03-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_favorite_watchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_changes', 'Needs Changes'), ('flagged', 'Flagged for Review'), ('festival', 'Festival')], default='pending', max_length=20),
        ),
    ]
