# Generated by Django 6.0.1 on 2026-03-31 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchhistory',
            name='last_watched_position',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='watch_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
