# Generated by Django 6.0.1 on 2026-02-18 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AwardVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='award.award')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_votes', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_votes', to='video.video')),
            ],
            options={
                'indexes': [models.Index(fields=['video', 'award'], name='award_award_video_i_71e03b_idx')],
                'unique_together': {('user', 'video', 'award')},
            },
        ),
        migrations.CreateModel(
            name='VideoAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_date', models.DateField(auto_now_add=True)),
                ('rank', models.IntegerField(blank=True, help_text='Ranking if applicable (1st, 2nd, 3rd)', null=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_awards', to='award.award')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='video.video')),
            ],
            options={
                'ordering': ['awarded_date'],
                'unique_together': {('video', 'award')},
            },
        ),
    ]
